services:
  app:
    image: "${BASE_IMAGE_NAME}-dev"
    build:
      context: .
      target: dev_image
    ports:
      # Use localhost so that we don't expose this to other machines.
      - '127.0.0.1:8866:8866'
    volumes:
      - .:/home/coder/src
      - "${UV_CACHE_DIR}:/home/coder/.cache/uv"
    environment:
      - VOILA_DEBUG=true
    command: ["uv", "run", "python", "app/voila-app.py"]
  jupyter:
    image: "${BASE_IMAGE_NAME}-dev"
    build:
      context: .
      target: dev_image
    ports:
      # Use localhost so that we don't expose this to other machines.
      - '127.0.0.1:8888:8888'
    volumes:
      - .:/home/coder/src
      - "${UV_CACHE_DIR}:/home/coder/.cache/uv"
    environment:
      - JUPYTERLAB_SETTINGS_DIR=/home/coder/src/jupyterlab/config
      - JUPYTERLAB_WORKSPACES_DIR=/home/coder/src/jupyterlab/workspaces
    command: ["uv", "run", "jupyter", "lab", "--ip", "0.0.0.0"]
