version: '3.4'
services:
  jupyter:
    image: "${BASE_IMAGE_NAME}-dev"
    build:
      context: .
      target: dev_image
    ports:
      - '8888:8888'
    volumes:
      - .:/home/coder/src
      - "${POETRY_CACHE_DIR}:/home/coder/.cache/pypoetry"
    environment:
      TZ: Pacific/Auckland
